# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AlarmOutcome(UniversalBaseModel):
    """
    One forecast-issued alarm under one alert threshold — the precision (cry-wolf) side.

    The complement to `EventOutcome`: every alert the forecast would have raised,
    whether or not it matched a real episode. Returned for the whole period so FAR /
    reissue burden can be computed across bins and thresholds client-side.
    """

    segment: str
    alarm_id: int
    bin: str
    threshold: float
    alarm_start: dt.datetime
    alarm_end: dt.datetime
    issued_lead_h: typing.Optional[float] = None
    max_prob: typing.Optional[float] = None
    n_reissues: int
    matched: bool
    matched_severity: typing.Optional[float] = None
    false_alarm: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
