# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .geo_location import GeoLocation


class CycloneForecastResponse(UniversalBaseModel):
    storm_id: str
    storm_name: str
    type: typing.Optional[str] = None
    category: int
    position: GeoLocation
    forecast_time: dt.datetime
    forecast_source_info: str
    forecast_last_updated: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
