# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DetectionPoint(UniversalBaseModel):
    """
    Detection rate (POD) for one (forecast day, severity, alert-threshold) cell.
    """

    lead_day: int
    severity: float
    prob: float
    n_events: int
    hits: int
    pod: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
