# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EventOutcome(UniversalBaseModel):
    """
    One observed event episode under one alert threshold — the recall (catch) side.

    Rows for the whole period (all bins, both thresholds) are returned so the UI can
    build the cross-aggregation operating-point view client-side; `warning_lead_h` is
    referenced to onset (null ⇒ the episode was never flagged at this threshold).
    """

    segment: str
    episode_id: int
    episode_start: dt.datetime
    episode_end: dt.datetime
    total_severity: float
    peak_window_severity: float
    bin: str
    threshold: float
    warning_lead_h: typing.Optional[float] = None
    n_crossings: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
