# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .forecast_row import ForecastRow


class ForecastTable(UniversalBaseModel):
    schema_version: typing.Optional[str] = None
    units: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    data: typing.List[ForecastRow]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
