# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic
from ..core.pydantic_utilities import update_forward_refs


class GeometryCollection(UniversalBaseModel):
    """
    GeometryCollection Model
    """

    bbox: typing.Optional[typing.List[typing.Optional[typing.Any]]] = None
    geometries: typing.List["GeometryCollectionGeometriesItem"]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .geometry_collection_geometries_item import GeometryCollectionGeometriesItem  # noqa: E402

update_forward_refs(GeometryCollection)
