# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GftusHourlyConditions(UniversalBaseModel):
    timestamp: dt.datetime
    temperature: typing.Optional[float] = None
    humidity: typing.Optional[int] = None
    wind_speed: typing.Optional[float] = None
    wind_gust: typing.Optional[float] = None
    wind_direction: typing.Optional[float] = None
    wind_speed_80_m: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="wind_speed_80m")] = None
    wind_direction_80_m: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="wind_direction_80m")
    ] = None
    dewpoint_temperature: typing.Optional[float] = None
    feels_like_temperature: typing.Optional[float] = None
    pressure: typing.Optional[float] = None
    precipitation_accumulation: typing.Optional[float] = None
    precipitation_probability: typing.Optional[int] = None
    cloud_cover: typing.Optional[int] = None
    downward_solar_radiation: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
