# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .hourly_conditions import HourlyConditions
from .hourly_weather_response_units import HourlyWeatherResponseUnits


class HourlyWeatherResponse(UniversalBaseModel):
    latitude: float
    longitude: float
    forecast_time: dt.datetime
    timezone: str
    utc_offset: int
    elevation: typing.Optional[int] = None
    units: HourlyWeatherResponseUnits
    hourly: typing.List[HourlyConditions]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
