# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ImperialUnits(UniversalBaseModel):
    elevation: typing.Optional[str] = None
    temperature: typing.Optional[str] = None
    feels_like_temperature: typing.Optional[str] = None
    precipitation_accumulation: typing.Optional[str] = None
    precipitation_probability: typing.Optional[str] = None
    snowfall_accumulation: typing.Optional[str] = None
    cloud_cover: typing.Optional[str] = None
    humidity: typing.Optional[str] = None
    wind_speed: typing.Optional[str] = None
    wind_direction: typing.Optional[str] = None
    dewpoint_temperature: typing.Optional[str] = None
    pressure: typing.Optional[str] = None
    downward_solar_radiation: typing.Optional[str] = None
    wind_speed_100_m: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="wind_speed_100m")] = None
    wind_direction_100_m: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="wind_direction_100m")
    ] = None
    global_horizontal_irradiation: typing.Optional[str] = None
    direct_normal_irradiation: typing.Optional[str] = None
    diffuse_horizontal_irradiation: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
