# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ImperialUnits(UniversalBaseModel):
    elevation: typing.Optional[str] = None
    temperature: typing.Optional[str] = None
    dewpoint_temperature: typing.Optional[str] = None
    precipitation_accumulation: typing.Optional[str] = None
    snowfall: typing.Optional[str] = None
    wind_speed: typing.Optional[str] = None
    wind_speed_100_m: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="wind_speed_100m")] = None
    pressure: typing.Optional[str] = None
    downward_solar_radiation: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
