# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alarm_outcome import AlarmOutcome
from .detection_point import DetectionPoint
from .event_outcome import EventOutcome
from .reliability_point import ReliabilityPoint
from .skill_by_lead_point import SkillByLeadPoint
from .skill_kpis import SkillKpis


class ScorecardModel(UniversalBaseModel):
    """
    Aggregate forecast-skill scorecard for a portfolio at one (period, bin) slice.
    """

    portfolio_id: str
    period: str
    bin: str
    model_version: typing.Optional[str] = None
    computed_at: typing.Optional[dt.datetime] = None
    kpi: SkillKpis
    skill_by_lead: typing.List[SkillByLeadPoint]
    reliability: typing.List[ReliabilityPoint]
    detection: typing.List[DetectionPoint]
    events: typing.Optional[typing.List[EventOutcome]] = None
    alarms: typing.Optional[typing.List[AlarmOutcome]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
