# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SkillKpis(UniversalBaseModel):
    """
    Headline verification KPIs for one (period, bin) slice.
    """

    pod: float
    far: float
    f_1: typing_extensions.Annotated[float, FieldMetadata(alias="f1"), pydantic.Field(alias="f1")]
    pr_auc: float
    brier: float
    brier_delta: typing.Optional[float] = None
    median_lead_h: typing.Optional[float] = None
    days_scored: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
