# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .vector_metric_counter import VectorMetricCounter
from .vector_metric_distribution import VectorMetricDistribution
from .vector_metric_gauge import VectorMetricGauge
from .vector_metric_histogram import VectorMetricHistogram
from .vector_metric_interval_ms import VectorMetricIntervalMs
from .vector_metric_kind import VectorMetricKind
from .vector_metric_set import VectorMetricSet
from .vector_metric_summary import VectorMetricSummary
from .vector_metric_timestamp import VectorMetricTimestamp


class VectorMetric(UniversalBaseModel):
    """
    VectorMetric is modelled on the Vector observability pipeline event schema:
    https://vector.dev/docs/about/under-the-hood/architecture/data-model/metric/

    Each metric carries a name, a tag map, a timestamp, a sampling interval, and
    exactly one value payload (counter, gauge, set, distribution, histogram, or
    summary).  Each metric may also have attributes, though these should be limited
    in cardinality as each attribute combination logically creates an independent
    metric series.

    The implementation here also allows for batched metric values of the same name,
    kind, and value payload for efficiency.
    """

    namespace: typing.Optional[str] = None
    name: str
    tags: typing.Dict[str, typing.Optional[str]]
    kind: VectorMetricKind
    timestamp: VectorMetricTimestamp
    interval_ms: VectorMetricIntervalMs
    counter: typing.Optional[VectorMetricCounter] = None
    gauge: typing.Optional[VectorMetricGauge] = None
    set_: typing_extensions.Annotated[
        typing.Optional[VectorMetricSet], FieldMetadata(alias="set"), pydantic.Field(alias="set")
    ] = None
    distribution: typing.Optional[VectorMetricDistribution] = None
    histogram: typing.Optional[VectorMetricHistogram] = None
    summary: typing.Optional[VectorMetricSummary] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
