# This file was auto-generated by Fern from our API Definition.

import typing

from .distribution import Distribution

VectorMetricDistribution = typing.Union[Distribution, typing.List[Distribution]]
